### ISSUE TITLE
Support playing MIDI from certain point in time 

### ISSUE THREAD

**Issue by lhl2617** [lhl2617/VSLilyPond#10]
Exploration: Start from certain point in time. 

I think starting from a certain beat or measure would be too complex. Will investigate.

**Comment by lhl2617** [comment]
#17 1.1.3 adds play from mm:ss timestamp

jzz-midi has no clear api on how to specify measure/beatnumber like in Frescobaldi. Will close this issue for now and investigate in the future on how to incorporate it. Might need a better MIDI library/write my own.

**Comment by jazz-soft** [comment]
MIDI file does not carry measure markers.
I guess the only robust method to draw the measure bars is to train an AI.
A good idea for a new project :)

**Comment by lhl2617** [comment]
@jazz-soft thanks

https://youtu.be/xdA1NLcBxLo

 9:20 shows Frescobaldi's feature working with measure numbers - I've tested with mixed time signatures and it works.

Here is the source code for the MIDI player Frescobaldi uses:
https://github.com/frescobaldi/frescobaldi/blob/09cae764126b505dedf0182beccd78d7934b2de4/frescobaldi_app/midifile/player.py

Any idea how it's implemented?

**Comment by jazz-soft** [comment]
Frescobaldi knows the positions of the bars because it has created the score.
I don't think that will work if you import a generic MIDI file.

**Comment by lhl2617** [comment]
Frescobaldi uses LilyPond to generate the MIDI file - so I'm guessing it has links back to the score using MIDI ticks. I will investigate further should there be more requests for this feature - thanks for the help!

**Comment by jazz-soft** [comment]
MIDI file normally has 96 ticks per quarter note (unless you change it explicitly)
If you know which beat you want to start, you know which tick to jump in the MIDI file.
