### ISSUE TITLE
How am I supposed to install lilypond?

### ISSUE THREAD

**Issue by kenNash** [lhl2617/VSLilyPond#14]
I'm sorry to bother you with this one...

I can't find any prescription on how to install lilypond in order for VSLilyPond to work as expected.

(I'm on macOS 10.15.4.)

Many TIA.
--
kN

**Comment by lhl2617** [comment]
Hi @kenNash 

See https://lilypond.org/macos-x.html.

You likely need to use the link for "Mac OS X x86 32-bit: LilyPond 2.20.0-1 For Mac OS X 10.4–10.5 running on Intel CPUs and Mac OS X 10.6–10.14 (for 10.15 see below)."

You then need to execute the five steps under "MacOS in the Command Line" under "Running on the command line".

After this, typing in "lilypond" in any terminal should bring it up.

Do let me know if you need help! I will be adding links to installation instructions on the readme.

**Comment by lhl2617** [comment]
Added setup guide in #15. See the setup guide file here: https://github.com/lhl2617/VSLilyPond/blob/dev/docs/INSTALL.md

**Comment by jazz-soft** [comment]
INSTALL.md says how to install the pre-requisits, but it does not say how to install VSLilyPond itself.
That would be really nice to add.

Thanks!

**Comment by lhl2617** [comment]
Thanks @jazz-soft , I will add the instructions.  Honoured to have you here - also would you mind looking at #10 ? Is there an API to get measure/beat numbers?

**Comment by lhl2617** [comment]
#21 adds VSLilyPond extension installation instructions

**Comment by jazz-soft** [comment]
MacOS 10.15.4, VS Code 1.44.2, LilyPond 2.20.0, VSLilyPond 1.1.6
getting the following error:
Intellisense failed with error ENOENT: no such file or directory, mkdir 'lilypondTmp'

Windows 10 - could not install VSLilyPond on VS Code 1.40.1 - not compatible with the current version.
Will update VS Code and try again...

**Comment by lhl2617** [comment]
@jazz-soft 
Windows problem: VsLilyPond is targeted to VSCode ^1.44.0, I will make this explicit in the requirements, thanks.

Mac: I currently do not have a Mac machine to test on but I will look into it, thanks for the heads up!

**Comment by lhl2617** [comment]
#22 should fix MacOS issue

**Comment by jazz-soft** [comment]
>  VsLilyPond is targeted to VSCode ^1.44.0
Does it use any particular VSCode features not available in previous versions?
why don't you target it to the earliest possible version?

**Comment by lhl2617** [comment]
> Does it use any particular VSCode features not available in previous versions?
> why don't you target it to the earliest possible version?

I wrote the extension based on the latest stable API - I'm not sure if it uses features not available in previous versions, but I'll have to set up envs for old versions if I wish to test it. Will look into this when I have time.
