### ISSUE TITLE
statusBar commands stop working

### ISSUE THREAD

**Issue by stef-levesque** [lhl2617/VSLilyPond#168]
Since the namespace change in cf9a8bba3e8b84c4a70c3fc2af72bacc87617f96, the statusBar shortcut stop working, since they are still using `extension.playMIDI` ...

Renaming them to `vslilypond.playMIDI`... in `src/miniIn.ts` and `src/miniOut.ts` will fix the issue.

**Comment by lhl2617** [comment]
Thanks for this--will fix

**Comment by lhl2617** [comment]
Resolved in 1.4.1 in #170.
