### ISSUE TITLE
Scheme syntax highlighting

### ISSUE THREAD

**Issue by jeandeaual** [lhl2617/VSLilyPond#174]
Thanks for the great extension!

Would it be possible to add support for [Scheme syntax](https://lilypond.org/doc/stable/Documentation/extending/lilypond-scheme-syntax) (in between `#(` and `)`) and comments (in between `#!` and `!#`)?
I'm not sure how to do that myself, but I'm willing to contribute if necessary.

**Comment by lhl2617** [comment]
Thanks for this @jeandeaual -- the formatting is based on an older vscode extension https://github.com/TrudyFirestone/VSLilyPond which does not support Scheme. That extension is in turn based on https://github.com/yrammos/SubLilyPond which _does_ support Scheme. 

I've personally not had the use for Scheme, so I didn't look into it--it is actually quite doable: https://github.com/TrudyFirestone/VSLilyPond has a guide on how to deal with the SubLilyPond files.

I unfortunately will not have any time to do this until Easter break (Apr-ish), but if you want to do it, go ahead! You can make your own extension that I can depend on, or you can pull it into here.

**Comment by jeandeaual** [comment]
Thanks for the information.

I'm working on an [updated syntax highlighter](https://github.com/jeandeaual/vscode-lilypond-syntax) based on https://github.com/TrudyFirestone/VSLilyPond but with Scheme support and LilyPond syntax updated for 2.23.
Making Scheme work is taking more time than expected since I'm still learning about making VSCode extensions.

I'll let you know when it's done!

**Comment by lhl2617** [comment]
@jeandeaual amazing! Thank you ;)

**Comment by lhl2617** [comment]
@jeandeaual https://github.com/TrudyFirestone/VSLilyPond/pull/1/files 

would you also kindly look at this and consider automatically closing chords' "<>"?

**Comment by jeandeaual** [comment]
> @jeandeaual https://github.com/TrudyFirestone/VSLilyPond/pull/1/files
> 
> would you also kindly look at this and consider automatically closing chords' "<>"?

[Done](https://github.com/jeandeaual/vscode-lilypond-syntax/commit/afec3f909a4f3c9a058a2ee2975c830bd2ba4d91)!

**Comment by lhl2617** [comment]
I see that https://marketplace.visualstudio.com/items?itemName=jeandeaual.lilypond-syntax is released! Will use this in place of the older highlighter :) Thanks @jeandeaual

**Comment by jeandeaual** [comment]
Thanks!
I still want to update keywords to what's available in LilyPond 2.22, but Scheme support is already implemented, so feel free to use it 🙂

**Comment by lhl2617** [comment]
Ah- unfortunately including this extension as a dependency causes VSLilyPond to not be able to initialise--I did not test this properly! Tracking in #206
