### ISSUE TITLE
Point-and-click on score?

### ISSUE THREAD

**Issue by xhevahir** [lhl2617/VSLilyPond#188]
I'm wondering if something like Frescobaldi's point-and-click functionality could be added, wherein a user can click on an element in the PDF score and have the mark jump to the corresponding place in the LilyPond code. (I see the LilyPond docs mention a `lilypond-invoke-editor` command?)

**Comment by lhl2617** [comment]
Hi @xhevahir -- thanks for this. This is indeed a convenient feature, and the docs are useful. However to have this built-in into the extension I think a custom pdf viewer for VSCode is required to invoke the correct command to link to the file.

I might be wrong--I'll look into this when I'm free next month :)

**Comment by Apostolique** [comment]
I have managed to add point and click a while ago. I don't know if I have the best setup, but this is what I did for Windows 10.

Get [SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf). It's a PDF reader that will update it's viewer when you regenerate the PDF. I edited a file called `sumatrapdfrestrict.ini` located in `C:\Program Files\SumatraPDF`. The `LinkProtocols` line says this:

```ini
; What protocols for links inside documents should be passed
; on to the operating system (e.g. for opening a browser).
; Default: http,https,mailto (web links and email addresses)
LinkProtocols = http,https,mailto,textedit
```

---

Launch Windows 10's registry editor (regedit) and expand `Computer\HKEY_CLASSES_ROOT\textedit\shell\open\command`

The key here should be named `(Default)`, type is `REG_EXPAND_SZ` and the data is `wscript C:\invisibleCommand.vbs "guile -s 'C:\Program Files (x86)\LilyPond\usr\bin\lilypond-invoke-editor' '%1'"`

---

Create a new file in `C:\` name it `invisibleCommand.vbs` set the content to: (You will need admin permissions.)
```vbs
command = wscript.arguments(0)

ReDim arr(WScript.Arguments.Count-1)
For i = 0 To WScript.Arguments.Count-1
  arr(i) = WScript.Arguments(i)
Next

command1 = Join(arr)
command2 = Replace(command1, "'", chr(34))

set shell = CreateObject("WScript.Shell")

shell.Run command2,0
```
`invisibleCommand.vbs` makes sure that there won't be a command prompt that will appear when you click on a note in the PDF.

---

I edited my `lilypond-invoke-editor` file which was located in `C:\Program Files (x86)\LilyPond\usr\bin`. The content is: <https://gist.github.com/Apostolique/b7af63d741aea07cac85d9ec520b2803>.

---

I added a new environment variable (write "environment in the window search"). The variable name is `LYEDITOR` and the value is `code -g %(file)s:%(line)s:%(column)s`.

---

I believe that's all I did. Maybe I edited `editor.scm` too, but I can't fully remember. If you have errors, feel free to post them here and I should remember.

**Comment by lhl2617** [comment]
@Apostolique Thanks for this! I've read more into the docs from lilypond as well, and wish to implement a extension using pdf.js to allow point and click in a VScode panel. No idea about its possibility, but I will continue to researxh

**Comment by Apostolique** [comment]
I'm pretty glad I wrote this, I just installed a new version of LilyPond and it required me to uninstall the old one. After I was done installing the new one my setup was overwritten. Feels good I could reapply these steps.

**Comment by lhl2617** [comment]
Sorry for the long wait but I finally found time to work on this!

I've began work on a Lilypond-focused PDF viewer -> https://github.com/lhl2617/VSLilyPond-PDF-preview

I'm currently investigating into issues with [PDF.js](https://github.com/mozilla/pdf.js) not rendering the `textedit:XXX` links--that should be the final hurdle in the whole process. I just then need to intercept those links into the PDF viewer back into vscode to point to the right cursor in the code.

The reverse is more complex, but I suppose it is not that difficult since the links have (x, y) coordinates and I just need to dig up the unfortunately not so great pdf.js API docs to learn how to scroll to the position.

I'll keep everyone posted.

**Comment by Apostolique** [comment]
Nice! I don't know if it helps, but I made this repo: <https://github.com/Apostolique/rust-lilypond-invoke-editor>.

**Comment by lhl2617** [comment]
> Nice! I don't know if it helps, but I made this repo: https://github.com/Apostolique/rust-lilypond-invoke-editor.

This is super cool :)

**Comment by lhl2617** [comment]
[v1.6.0](https://github.com/lhl2617/VSLilyPond/tree/v1.6.0) now supports point-and-click with a [custom PDF viewer](https://marketplace.visualstudio.com/items?itemName=lhl2617.lilypond-pdf-preview).

**Comment by Apostolique** [comment]
Nice job! This is way more instant than what I had before.
