### ISSUE TITLE
Including `jeandeaual.lilypond-syntax` as an extension dependency causes VSLilyPond to not initiatlise

### ISSUE THREAD

**Issue by lhl2617** [lhl2617/VSLilyPond#206]
![image](https://user-images.githubusercontent.com/33488131/111890400-e3a73d80-89e0-11eb-98ea-162f399161d7.png)

**Comment by lhl2617** [comment]
To be investigated--currently 1.5.2 #205 will recommend the extension as an optional requirement. Strangely, installing that extension separately but not as a dependency works...

**Comment by lhl2617** [comment]
Reproduction:
```
git checkout issue-206
```
Hit F5 to enter Extension Development Host

Errors appear as notifications:
![image](https://user-images.githubusercontent.com/33488131/111890503-c9219400-89e1-11eb-80a9-837045821273.png)

and also in development console 
![image](https://user-images.githubusercontent.com/33488131/111890509-d179cf00-89e1-11eb-8a18-c51dbb589f53.png)

**Comment by lhl2617** [comment]
Error source is confirmed to be in `sjhuangx.vscode-scheme` (https://marketplace.visualstudio.com/items?itemName=sjhuangx.vscode-scheme). 

Running this extension by itself gives 
![image](https://user-images.githubusercontent.com/33488131/111891083-b7db8600-89e7-11eb-8643-780084559cc5.png)
and in dev console
![image](https://user-images.githubusercontent.com/33488131/111891086-bf029400-89e7-11eb-9aca-ab5a11e1beea.png)

**Comment by lhl2617** [comment]
@jeandeaual -- wondering if you have seen this when you included the extension as a dep?

**Comment by jeandeaual** [comment]
I didn't, but I think I had it manually installed when developing. I'll take a look at that and let you know when it's fixed!

**Comment by lhl2617** [comment]
Currently tinkering with src of `sjhuangx.vscode-scheme`: https://github.com/sjhuangx/vscode-scheme

https://github.com/sjhuangx/vscode-scheme/blob/9bd15efa411cef23955df314f8d9399057d068de/src/schemeMain.ts#L5

seems to be the source of the error. Commenting this line out solves the problem. This extension uses outdated dependencies, which may be an issue.

**Comment by lhl2617** [comment]
Found bug source.

https://github.com/sjhuangx/vscode-scheme/blob/9bd15efa411cef23955df314f8d9399057d068de/src/schemeConfiguration.ts#L6


`decreaseIndentPattern` should not be `undefined`: https://code.visualstudio.com/api/references/vscode-api#IndentationRule

**Comment by lhl2617** [comment]
PR with fix created: https://github.com/sjhuangx/vscode-scheme/pull/13

**Comment by lhl2617** [comment]
> I didn't, but I think I had it manually installed when developing. I'll take a look at that and let you know when it's fixed!

@jeandeaual Ah--it's clear now why you didn't see it. Your extension does not "activate"--it just loads the syntaxes. If it activates, the above errors will occur.

The scheme extension seems unmaintained as of now--maintaining unpopular OSS projects takes effort after all, but I hope the fixes can be incorporated.

**Comment by jeandeaual** [comment]
I see, thanks for the research. The official guide for syntax highlighting extensions don't say anything about activation.
The Scheme extension doesn't seem to be maintained anymore so I was planning to fork it at some point.
I'll try to fix the issue sometime this week.

**Comment by lhl2617** [comment]
Keen to see more amazing work on the syntax highlighter :)

**Comment by jeandeaual** [comment]
This should now be fixed with [`jeandeaual.lilypond-syntax` v0.1.1](https://github.com/jeandeaual/vscode-lilypond-syntax/releases/tag/v0.1.1), which now uses [my own Scheme extension](https://github.com/jeandeaual/vscode-scheme).

**Comment by lhl2617** [comment]
No worries! Not your fault :) Immense thanks for all the great work! Will release a new version with your extension as a dep.

**Comment by lhl2617** [comment]
Fixed in 1.5.4 (#219)
