### ISSUE TITLE
Add a `Building...` status bar item when compiling

### ISSUE THREAD

**Issue by lhl2617** [lhl2617/VSLilyPond#252]
Similar to LaTeX workshop's

**Comment by Apostolique** [comment]
Related to that, if building is slow perhaps due to a large file and you save twice really fast, the second time will show an error. (I can post the error message later if needed.)

It could be nice to queue the second save. Or maybe abort the first one.

**Comment by lhl2617** [comment]
> Related to that, if building is slow perhaps due to a large file and you save twice really fast, the second time will show an error. (I can post the error message later if needed.)

I reckon it's this:

https://github.com/lhl2617/VSLilyPond/blob/9aaeb7a73d0418f7506947b53d6eb2a5956d8577/src/lilypond.ts#L137

**Comment by lhl2617** [comment]
Created #253 to track (queueing/concurrent) compilations
