### ISSUE TITLE
Could not pull "Apple DLS Synth" or "Network Session 1" to set Midi Input and Playback on "Big Sur"

### ISSUE THREAD

**Issue by zhou** [lhl2617/VSLilyPond#334]
It was all good on Catalina. But when I tried VSLilyPond on a new MacBook Air with Big Sur, in either MIDI Playback or MIDI Input, the list is empty. 

The built-in Apple DLS Synth would be a good, quick way to test out the music without depending on an external MIDI device. 

For the "Network Session 1", I am using expressionPad as the MIDI controller / pad. It works great with GarageBand on both Catalina and Big Sur. And on the Catalina, in VSLilyPond, the expressionPad works great for the MIDI Input. However, it doesn't work for VSLilyPond on Big Sur. 

I'm not sure whether upgrading the JZZ library to the latest version would help. But it might worth trying. Thanks

**Comment by lhl2617** [comment]
Thanks for reporting this--let me experiment

**Comment by lhl2617** [comment]
I've bumped jzz to the latest in 1.7.0--I haven't got any Macs currently to test this, can you see if that fixed the problem

**Comment by lhl2617** [comment]
closed due to inactivity
