### ISSUE TITLE
MIDI input is not debounced

### ISSUE THREAD

**Issue by paradox460** [lhl2617/VSLilyPond#341]
I am using a KORG microKEY AIR (bluetooth 25key midi keyboard) on MacOS 10.15.7, and when attempting to input notes, I get a "double note" effect. Pressing the key gets one note entered into the document, but releasing it gets the same note.

Additionally, there is some carry-over from previously entered notes.

![Screenshot 2021-09-03 at 15 27 12](https://user-images.githubusercontent.com/168193/132066840-313c88fc-540e-4e0c-bb4c-7d47ecb22125.gif)

**Comment by paradox460** [comment]
Investigating a bit more, it looks like the velocity on key release is 64

<img width="359" alt="Screenshot 2021-09-03 at 20 23 40@2x" src="https://user-images.githubusercontent.com/168193/132079388-009c0cb9-8d3b-4e3f-bf62-f3611e0bdb28.png">

**Comment by lhl2617** [comment]
Thank you so much for this--merging into dev and I will be checking tomorrow before releasing a new version.
