### ISSUE TITLE
Select a sound font for MIDI player

### ISSUE THREAD

**Issue by alensiljak** [lhl2617/VSLilyPond#357]
Is it possible to select a custom sound font for the MIDI player? Would it be possible to add, if not?

**Comment by lhl2617** [comment]
Heya! On the top of my mind, you'd need to set up a virtual MIDI output device, then link that to your soundfont. You can set VSLilyPond to use that output device as per https://github.com/lhl2617/VSLilyPond/blob/master/docs/COMMANDS.md#vslilypond-midi-playback-set-output-device
