### ISSUE TITLE
Cannot play MIDI file from VSLilyPond

### ISSUE THREAD

**Issue by jbfavre** [lhl2617/VSLilyPond#36]
I've read the FAQ.
Midi output is well generated (works like a charm with Frescobaldi or lilypond itself)

**Problem**:
Currently, MIDI file extension is hardcoded to `.mid` in file https://github.com/lhl2617/VSLilyPond/blob/master/src/midiOut.ts#L90
By default, lilypond will use `.midi`, except for Windows:

    (midi-extension ,(if (eq? PLATFORM 'windows)
                         "mid"
                         "midi")

Possible solutions:
* allow changing extension in settings
* find a way to get it from lilypond defaults
* detect the platform and use lilypond default (hoping users doesn't override it)
* test for both `.mid` and `.midi`
* force a preferred extension as option when compiling lilypond file (see http://lilypond.org/doc/v2.20/Documentation/notation/the-midi-block.html)

**Comment by lhl2617** [comment]
Thanks - I will look into this today. I am likely to go for the check for both "mid" and "midi" option

**Comment by lhl2617** [comment]
Fix performed in #37:

Finds midi file by following the sequence
1) Look for `.midi` extension
2) Look for `.mid` extension
3) Look in the directory for files having same filenames (or with extra characters e.g. `-1`) as the LilyPond file, returning the first one with mime-type `audio/midi`.

-
Step 3 solves problems with custom extensions in an OS-agnostic way without getting too much in the way of LilyPond itself.

**Comment by jbfavre** [comment]
Works perfectly well.
Thanks for fixing it quickly !

**Comment by lhl2617** [comment]
Thank you very much for the detailed issue report and proposed fixes :D
