### ISSUE TITLE
Customize lilypond exectuable path in plugin settings

### ISSUE THREAD

**Issue by yanghu** [lhl2617/VSLilyPond#39]
Is it possible to configure lilypond binary path in the plugin settings?
(in case that one do not want to add lilypond path to PATH)

**Comment by lhl2617** [comment]
Hi @yanghu - thanks for the issue, this is planned and will come soon :)

**Comment by lhl2617** [comment]
Had some time so I implemented it -- released in #40 (1.1.10)
