### ISSUE TITLE
Upgrade dependencies to include jazz-midi 1.7.3

### ISSUE THREAD

**Issue by rschroll** [lhl2617/VSLilyPond#99]
I was trying the midi input feature, and I found that only the occasional keypress was being recognized by VSLilyPond. After some troubleshooting, I found that this was a problem in the jazz-midi package used by JZZ: https://github.com/jazz-soft/JZZ/issues/26#issuecomment-637936110.  It was recently fixed in 1.7.3.  I forced an upgrade in my install of VSLilypond, and all keypresses are now registered.

**Comment by lhl2617** [comment]
Thanks for reporting and investigating :) 
Bumped VSLilyPond to 1.3.1 (#101). Published and should be out soon :D
